stages:
  - build

build_image:
  stage: build
  tags:
    - build

  rules:
  - if: '$CI_COMMIT_REF_PROTECTED == "true"'

  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  before_script:
    - echo "$REGISTRY_PUSH_PASSWORD" | docker login $REGISTRY_SERVER -u $REGISTRY_PUSH_USER --password-stdin

  script:
    - export APP_VERSION=$(date +'%Y-%m-%d_%H-%M-%S')-`[ -n "$CI_COMMIT_TAG" ] && echo $CI_COMMIT_TAG || echo $CI_COMMIT_SHORT_SHA` && echo $APP_VERSION
    - docker build --cache-from "$REGISTRY_IMAGE:latest" -t "$REGISTRY_IMAGE:$APP_VERSION" -t "$REGISTRY_IMAGE"  . -f Dockerfile
    - docker push "$REGISTRY_IMAGE:$APP_VERSION"


